version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my_network

  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
